version: '3.7'

services:
  backend: &backend
    build:
      context: .
      dockerfile: .docker/Dockerfile_base
    command: shell
    env_file:
      - ./.docker/envs/db.env
      - ./.docker/envs/back.env
    environment:
      # forwarded from the host if they exist
      - UPDATE_PYTHON_REQUIREMENTS_ON_CONTAINERSTART
    volumes:
      - .:/opt/cornershop/backend-test
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
  jupyterlab:
    <<: *backend
    command: jupyterlab
    ports:
      - 8001:8000
  postgres:
    image: circleci/postgres:12.3-postgis
    volumes:
      - postgres123-data:/var/lib/postgresql/data/
    env_file:
      - ./.docker/envs/db.env
    ports:
      - 5432:5432
  testdb:
    image: circleci/postgres:12.3-postgis-ram
    env_file:
      - ./.docker/envs/db.env
    ports:
      - 5433:5432
  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-data:/data

volumes:
  postgres123-data: {}
  redis-data: {}
  elasticsearch-data: {}
  dynamodb-data: {}
  neo4j-data: {}

