# Generated by Django 3.0.8 on 2021-04-13 05:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=100)),
                ('side_order', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'dishes',
                'db_table': 'dish',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('dishes', models.ManyToManyField(related_name='dishes_in_menu', to='lunchs.Dish')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunchs.Dish')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
